// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: obadafoundation/obit/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryGetNFTRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetNFTRequest) Reset()         { *m = QueryGetNFTRequest{} }
func (m *QueryGetNFTRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetNFTRequest) ProtoMessage()    {}
func (*QueryGetNFTRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_66271424c3412545, []int{0}
}
func (m *QueryGetNFTRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetNFTRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetNFTRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetNFTRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetNFTRequest.Merge(m, src)
}
func (m *QueryGetNFTRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetNFTRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetNFTRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetNFTRequest proto.InternalMessageInfo

func (m *QueryGetNFTRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type QueryGetNFTByAddressRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryGetNFTByAddressRequest) Reset()         { *m = QueryGetNFTByAddressRequest{} }
func (m *QueryGetNFTByAddressRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetNFTByAddressRequest) ProtoMessage()    {}
func (*QueryGetNFTByAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_66271424c3412545, []int{1}
}
func (m *QueryGetNFTByAddressRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetNFTByAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetNFTByAddressRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetNFTByAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetNFTByAddressRequest.Merge(m, src)
}
func (m *QueryGetNFTByAddressRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetNFTByAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetNFTByAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetNFTByAddressRequest proto.InternalMessageInfo

func (m *QueryGetNFTByAddressRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type QueryGetNFTByAddressResponse struct {
	NFT []NFT `protobuf:"bytes,1,rep,name=NFT,proto3" json:"NFT"`
}

func (m *QueryGetNFTByAddressResponse) Reset()         { *m = QueryGetNFTByAddressResponse{} }
func (m *QueryGetNFTByAddressResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetNFTByAddressResponse) ProtoMessage()    {}
func (*QueryGetNFTByAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_66271424c3412545, []int{2}
}
func (m *QueryGetNFTByAddressResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetNFTByAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetNFTByAddressResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetNFTByAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetNFTByAddressResponse.Merge(m, src)
}
func (m *QueryGetNFTByAddressResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetNFTByAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetNFTByAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetNFTByAddressResponse proto.InternalMessageInfo

func (m *QueryGetNFTByAddressResponse) GetNFT() []NFT {
	if m != nil {
		return m.NFT
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryGetNFTRequest)(nil), "obadafoundation.obit.v1.QueryGetNFTRequest")
	proto.RegisterType((*QueryGetNFTByAddressRequest)(nil), "obadafoundation.obit.v1.QueryGetNFTByAddressRequest")
	proto.RegisterType((*QueryGetNFTByAddressResponse)(nil), "obadafoundation.obit.v1.QueryGetNFTByAddressResponse")
}

func init() {
	proto.RegisterFile("obadafoundation/obit/v1/query.proto", fileDescriptor_66271424c3412545)
}

var fileDescriptor_66271424c3412545 = []byte{
	// 402 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x4f, 0x8b, 0xda, 0x40,
	0x18, 0xc6, 0x33, 0xb1, 0xb5, 0x74, 0x0a, 0x2d, 0x0c, 0x85, 0x8a, 0x95, 0xd4, 0xc6, 0x16, 0xa4,
	0xb6, 0x19, 0x62, 0x2d, 0x3d, 0xd7, 0x83, 0x3d, 0x14, 0x84, 0x8a, 0xa7, 0xde, 0x26, 0x66, 0x4c,
	0x07, 0x62, 0xde, 0x98, 0x99, 0x48, 0xa5, 0x08, 0xcb, 0x7e, 0x82, 0x85, 0xfd, 0x2a, 0xfb, 0x05,
	0xf6, 0xe6, 0x51, 0xd8, 0xcb, 0x9e, 0x96, 0x45, 0xf7, 0x83, 0x2c, 0xc9, 0x28, 0x88, 0xac, 0xee,
	0xee, 0x2d, 0x7f, 0x7e, 0xcf, 0xf3, 0x3e, 0xef, 0xc3, 0x8b, 0x6b, 0xe0, 0x31, 0x9f, 0x0d, 0x21,
	0x8d, 0x7c, 0xa6, 0x04, 0x44, 0x14, 0x3c, 0xa1, 0xe8, 0xc4, 0xa5, 0xe3, 0x94, 0x27, 0x53, 0x27,
	0x4e, 0x40, 0x01, 0x79, 0xb3, 0x03, 0x39, 0x19, 0xe4, 0x4c, 0xdc, 0xf2, 0xeb, 0x00, 0x02, 0xc8,
	0x19, 0x9a, 0x3d, 0x69, 0xbc, 0x5c, 0x09, 0x00, 0x82, 0x90, 0x53, 0x16, 0x0b, 0xca, 0xa2, 0x08,
	0x54, 0x2e, 0x92, 0xeb, 0xbf, 0x9f, 0x06, 0x20, 0x47, 0x20, 0xa9, 0xc7, 0x24, 0xd7, 0x53, 0xe8,
	0xc4, 0xf5, 0xb8, 0x62, 0x2e, 0x8d, 0x59, 0x20, 0x22, 0x3d, 0x41, 0xb3, 0xef, 0xf7, 0xa5, 0x8b,
	0x86, 0x4a, 0x23, 0xf6, 0x07, 0x4c, 0x7e, 0x67, 0x26, 0x3f, 0xb9, 0xea, 0x76, 0xfa, 0x3d, 0x3e,
	0x4e, 0xb9, 0x54, 0xe4, 0x25, 0x36, 0x85, 0x5f, 0x42, 0x55, 0x54, 0x7f, 0xde, 0x33, 0x85, 0x6f,
	0x7f, 0xc7, 0x6f, 0xb7, 0xa8, 0xf6, 0xf4, 0x87, 0xef, 0x27, 0x5c, 0xca, 0x0d, 0x5e, 0xc2, 0xcf,
	0x98, 0xfe, 0xb2, 0xd6, 0x6c, 0x5e, 0xed, 0x3e, 0xae, 0xdc, 0x2d, 0x94, 0x31, 0x44, 0x92, 0x93,
	0x16, 0x2e, 0x74, 0x3b, 0xfd, 0x12, 0xaa, 0x16, 0xea, 0x2f, 0x9a, 0x15, 0x67, 0x4f, 0x51, 0x4e,
	0xa6, 0x7d, 0x32, 0xbf, 0x7a, 0x67, 0xf4, 0x32, 0xbc, 0x79, 0x6e, 0xe2, 0xa7, 0xb9, 0x2d, 0x39,
	0x43, 0xf8, 0xd5, 0x8e, 0x37, 0x69, 0xed, 0xb5, 0x39, 0xb0, 0x43, 0xf9, 0xdb, 0x23, 0x55, 0x7a,
	0x01, 0xbb, 0x75, 0x7c, 0x71, 0x73, 0x6a, 0x3a, 0xe4, 0x33, 0xcd, 0xe5, 0x5f, 0xb6, 0xca, 0x1e,
	0xa6, 0x61, 0x38, 0x80, 0x84, 0x67, 0x6d, 0xd3, 0xff, 0xeb, 0x46, 0x66, 0x94, 0x85, 0x21, 0x39,
	0x42, 0xb8, 0xa8, 0x1d, 0x49, 0xe3, 0x21, 0x73, 0x37, 0x21, 0x0f, 0x36, 0x64, 0x37, 0xf2, 0x2c,
	0x1f, 0x49, 0xed, 0xbe, 0x2c, 0xc2, 0x9f, 0xb5, 0x7f, 0xcd, 0x97, 0x16, 0x5a, 0x2c, 0x2d, 0x74,
	0xbd, 0xb4, 0xd0, 0xc9, 0xca, 0x32, 0x16, 0x2b, 0xcb, 0xb8, 0x5c, 0x59, 0xc6, 0x1f, 0x37, 0x10,
	0xea, 0x6f, 0xea, 0x39, 0x03, 0x18, 0x1d, 0x30, 0xfa, 0xa7, 0x8f, 0x49, 0x4d, 0x63, 0x2e, 0xbd,
	0x62, 0x7e, 0x4c, 0x5f, 0x6f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x4b, 0x7a, 0x67, 0x57, 0x0f, 0x03,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// QueryGetAllNFTByAddressRequest returns a list of NFTs ownerd by given
	// address
	GetNFTByAddress(ctx context.Context, in *QueryGetNFTByAddressRequest, opts ...grpc.CallOption) (*QueryGetNFTByAddressResponse, error)
	// GetNft returns single NFT by DID
	GetNFT(ctx context.Context, in *QueryGetNFTRequest, opts ...grpc.CallOption) (*NFT, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) GetNFTByAddress(ctx context.Context, in *QueryGetNFTByAddressRequest, opts ...grpc.CallOption) (*QueryGetNFTByAddressResponse, error) {
	out := new(QueryGetNFTByAddressResponse)
	err := c.cc.Invoke(ctx, "/obadafoundation.obit.v1.Query/GetNFTByAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetNFT(ctx context.Context, in *QueryGetNFTRequest, opts ...grpc.CallOption) (*NFT, error) {
	out := new(NFT)
	err := c.cc.Invoke(ctx, "/obadafoundation.obit.v1.Query/GetNFT", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// QueryGetAllNFTByAddressRequest returns a list of NFTs ownerd by given
	// address
	GetNFTByAddress(context.Context, *QueryGetNFTByAddressRequest) (*QueryGetNFTByAddressResponse, error)
	// GetNft returns single NFT by DID
	GetNFT(context.Context, *QueryGetNFTRequest) (*NFT, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) GetNFTByAddress(ctx context.Context, req *QueryGetNFTByAddressRequest) (*QueryGetNFTByAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNFTByAddress not implemented")
}
func (*UnimplementedQueryServer) GetNFT(ctx context.Context, req *QueryGetNFTRequest) (*NFT, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNFT not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_GetNFTByAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetNFTByAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetNFTByAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/obadafoundation.obit.v1.Query/GetNFTByAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetNFTByAddress(ctx, req.(*QueryGetNFTByAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetNFT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetNFTRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetNFT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/obadafoundation.obit.v1.Query/GetNFT",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetNFT(ctx, req.(*QueryGetNFTRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "obadafoundation.obit.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNFTByAddress",
			Handler:    _Query_GetNFTByAddress_Handler,
		},
		{
			MethodName: "GetNFT",
			Handler:    _Query_GetNFT_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "obadafoundation/obit/v1/query.proto",
}

func (m *QueryGetNFTRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetNFTRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetNFTRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetNFTByAddressRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetNFTByAddressRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetNFTByAddressRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetNFTByAddressResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetNFTByAddressResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetNFTByAddressResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.NFT) > 0 {
		for iNdEx := len(m.NFT) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.NFT[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryGetNFTRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetNFTByAddressRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetNFTByAddressResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.NFT) > 0 {
		for _, e := range m.NFT {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryGetNFTRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetNFTRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetNFTRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetNFTByAddressRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetNFTByAddressRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetNFTByAddressRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetNFTByAddressResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetNFTByAddressResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetNFTByAddressResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NFT", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NFT = append(m.NFT, NFT{})
			if err := m.NFT[len(m.NFT)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
