// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: obit/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b91743c0fd69115, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b91743c0fd69115, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetAllNftByOwnerRequest struct {
	Owner string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
}

func (m *QueryGetAllNftByOwnerRequest) Reset()         { *m = QueryGetAllNftByOwnerRequest{} }
func (m *QueryGetAllNftByOwnerRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetAllNftByOwnerRequest) ProtoMessage()    {}
func (*QueryGetAllNftByOwnerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b91743c0fd69115, []int{2}
}
func (m *QueryGetAllNftByOwnerRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetAllNftByOwnerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetAllNftByOwnerRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetAllNftByOwnerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetAllNftByOwnerRequest.Merge(m, src)
}
func (m *QueryGetAllNftByOwnerRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetAllNftByOwnerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetAllNftByOwnerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetAllNftByOwnerRequest proto.InternalMessageInfo

func (m *QueryGetAllNftByOwnerRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type QueryGetAllNftByOwnerResponse struct {
	NFT []NFT `protobuf:"bytes,1,rep,name=NFT,proto3" json:"NFT"`
}

func (m *QueryGetAllNftByOwnerResponse) Reset()         { *m = QueryGetAllNftByOwnerResponse{} }
func (m *QueryGetAllNftByOwnerResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetAllNftByOwnerResponse) ProtoMessage()    {}
func (*QueryGetAllNftByOwnerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b91743c0fd69115, []int{3}
}
func (m *QueryGetAllNftByOwnerResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetAllNftByOwnerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetAllNftByOwnerResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetAllNftByOwnerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetAllNftByOwnerResponse.Merge(m, src)
}
func (m *QueryGetAllNftByOwnerResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetAllNftByOwnerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetAllNftByOwnerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetAllNftByOwnerResponse proto.InternalMessageInfo

func (m *QueryGetAllNftByOwnerResponse) GetNFT() []NFT {
	if m != nil {
		return m.NFT
	}
	return nil
}

type QueryGetTaRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetTaRequest) Reset()         { *m = QueryGetTaRequest{} }
func (m *QueryGetTaRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetTaRequest) ProtoMessage()    {}
func (*QueryGetTaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b91743c0fd69115, []int{4}
}
func (m *QueryGetTaRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetTaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetTaRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetTaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetTaRequest.Merge(m, src)
}
func (m *QueryGetTaRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetTaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetTaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetTaRequest proto.InternalMessageInfo

func (m *QueryGetTaRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetTaResponse struct {
	Ta Ta `protobuf:"bytes,1,opt,name=Ta,proto3" json:"Ta"`
}

func (m *QueryGetTaResponse) Reset()         { *m = QueryGetTaResponse{} }
func (m *QueryGetTaResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetTaResponse) ProtoMessage()    {}
func (*QueryGetTaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b91743c0fd69115, []int{5}
}
func (m *QueryGetTaResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetTaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetTaResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetTaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetTaResponse.Merge(m, src)
}
func (m *QueryGetTaResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetTaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetTaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetTaResponse proto.InternalMessageInfo

func (m *QueryGetTaResponse) GetTa() Ta {
	if m != nil {
		return m.Ta
	}
	return Ta{}
}

type QueryAllTaRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllTaRequest) Reset()         { *m = QueryAllTaRequest{} }
func (m *QueryAllTaRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllTaRequest) ProtoMessage()    {}
func (*QueryAllTaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b91743c0fd69115, []int{6}
}
func (m *QueryAllTaRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllTaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllTaRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllTaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllTaRequest.Merge(m, src)
}
func (m *QueryAllTaRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllTaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllTaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllTaRequest proto.InternalMessageInfo

func (m *QueryAllTaRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllTaResponse struct {
	Ta         []Ta                `protobuf:"bytes,1,rep,name=Ta,proto3" json:"Ta"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllTaResponse) Reset()         { *m = QueryAllTaResponse{} }
func (m *QueryAllTaResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllTaResponse) ProtoMessage()    {}
func (*QueryAllTaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b91743c0fd69115, []int{7}
}
func (m *QueryAllTaResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllTaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllTaResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllTaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllTaResponse.Merge(m, src)
}
func (m *QueryAllTaResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllTaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllTaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllTaResponse proto.InternalMessageInfo

func (m *QueryAllTaResponse) GetTa() []Ta {
	if m != nil {
		return m.Ta
	}
	return nil
}

func (m *QueryAllTaResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "obadafoundation.fullcore.obit.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "obadafoundation.fullcore.obit.QueryParamsResponse")
	proto.RegisterType((*QueryGetAllNftByOwnerRequest)(nil), "obadafoundation.fullcore.obit.QueryGetAllNftByOwnerRequest")
	proto.RegisterType((*QueryGetAllNftByOwnerResponse)(nil), "obadafoundation.fullcore.obit.QueryGetAllNftByOwnerResponse")
	proto.RegisterType((*QueryGetTaRequest)(nil), "obadafoundation.fullcore.obit.QueryGetTaRequest")
	proto.RegisterType((*QueryGetTaResponse)(nil), "obadafoundation.fullcore.obit.QueryGetTaResponse")
	proto.RegisterType((*QueryAllTaRequest)(nil), "obadafoundation.fullcore.obit.QueryAllTaRequest")
	proto.RegisterType((*QueryAllTaResponse)(nil), "obadafoundation.fullcore.obit.QueryAllTaResponse")
}

func init() { proto.RegisterFile("obit/query.proto", fileDescriptor_3b91743c0fd69115) }

var fileDescriptor_3b91743c0fd69115 = []byte{
	// 587 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0x41, 0x6b, 0x13, 0x4f,
	0x18, 0xc6, 0x33, 0x9b, 0x26, 0xf0, 0x9f, 0xf2, 0x2f, 0xed, 0x98, 0x43, 0x09, 0xed, 0x5a, 0x47,
	0x6b, 0x6a, 0xa1, 0x33, 0x26, 0x0a, 0x82, 0x7a, 0x49, 0x84, 0xf4, 0x20, 0xc6, 0x1a, 0xf6, 0xd4,
	0x9e, 0x66, 0x93, 0xc9, 0xba, 0xb0, 0xd9, 0xd9, 0x66, 0x27, 0x6a, 0x28, 0xbd, 0xf8, 0x09, 0x04,
	0x41, 0xc4, 0x83, 0xe0, 0x17, 0xf1, 0xdc, 0x63, 0xc1, 0x8b, 0x27, 0x91, 0xc4, 0x0f, 0x22, 0x3b,
	0x33, 0xa1, 0x49, 0xb4, 0xdd, 0xc4, 0x5b, 0xde, 0xc9, 0xfb, 0xbc, 0xcf, 0x2f, 0x6f, 0x9e, 0x19,
	0xb8, 0x2a, 0x5c, 0x5f, 0xd2, 0xe3, 0x3e, 0xef, 0x0d, 0x48, 0xd4, 0x13, 0x52, 0xa0, 0x4d, 0xe1,
	0xb2, 0x36, 0xeb, 0x88, 0x7e, 0xd8, 0x66, 0xd2, 0x17, 0x21, 0xe9, 0xf4, 0x83, 0xa0, 0x25, 0x7a,
	0x9c, 0x24, 0xad, 0xc5, 0x82, 0x27, 0x3c, 0xa1, 0x3a, 0x69, 0xf2, 0x49, 0x8b, 0x8a, 0x1b, 0x9e,
	0x10, 0x5e, 0xc0, 0x29, 0x8b, 0x7c, 0xca, 0xc2, 0x50, 0x48, 0x25, 0x8d, 0xcd, 0xb7, 0xbb, 0x2d,
	0x11, 0x77, 0x45, 0x4c, 0x5d, 0x16, 0x73, 0xed, 0x45, 0x5f, 0x95, 0x5d, 0x2e, 0x59, 0x99, 0x46,
	0xcc, 0xf3, 0x43, 0xed, 0xa3, 0x7b, 0xd7, 0x14, 0x50, 0xc4, 0x7a, 0xac, 0x3b, 0x96, 0xff, 0xaf,
	0x8e, 0x24, 0x33, 0xe5, 0x8a, 0x2a, 0xc3, 0x8e, 0xd4, 0x35, 0x2e, 0x40, 0xf4, 0x22, 0x99, 0x79,
	0xa0, 0x34, 0x4d, 0x7e, 0xdc, 0xe7, 0xb1, 0xc4, 0x87, 0xf0, 0xda, 0xd4, 0x69, 0x1c, 0x89, 0x30,
	0xe6, 0xe8, 0x09, 0xcc, 0xeb, 0xd9, 0xeb, 0x60, 0x0b, 0xec, 0x2c, 0x57, 0xb6, 0xc9, 0x95, 0x3f,
	0x97, 0x68, 0x79, 0x6d, 0xe9, 0xec, 0xc7, 0xf5, 0x4c, 0xd3, 0x48, 0xf1, 0x7d, 0xb8, 0xa1, 0x66,
	0xef, 0x73, 0x59, 0x0d, 0x82, 0x46, 0x47, 0xd6, 0x06, 0xcf, 0x5f, 0x87, 0xbc, 0x67, 0xbc, 0x51,
	0x01, 0xe6, 0x44, 0x52, 0x2b, 0x8f, 0xff, 0x9a, 0xba, 0xc0, 0x47, 0x70, 0xf3, 0x12, 0x95, 0x61,
	0x7b, 0x08, 0xb3, 0x8d, 0xba, 0xb3, 0x0e, 0xb6, 0xb2, 0x3b, 0xcb, 0x15, 0x9c, 0x02, 0xd6, 0xa8,
	0x3b, 0x86, 0x2a, 0x11, 0xe1, 0x9b, 0x70, 0x6d, 0x3c, 0xdc, 0x61, 0x63, 0x8e, 0x15, 0x68, 0xf9,
	0x6d, 0x05, 0xb1, 0xd4, 0xb4, 0xfc, 0x36, 0x7e, 0x66, 0x36, 0x65, 0x9a, 0x8c, 0xed, 0x03, 0x68,
	0x39, 0xcc, 0xac, 0xe3, 0x46, 0x8a, 0xab, 0xc3, 0x8c, 0xa9, 0xe5, 0x30, 0x7c, 0x64, 0x3c, 0xab,
	0x41, 0x70, 0xe1, 0x59, 0x87, 0xf0, 0xe2, 0x3f, 0x35, 0x53, 0x6f, 0x13, 0x1d, 0x00, 0x92, 0x04,
	0x80, 0xe8, 0xb0, 0x99, 0x00, 0x90, 0x03, 0xe6, 0x71, 0xa3, 0x6d, 0x4e, 0x28, 0xf1, 0x07, 0x60,
	0x60, 0xcd, 0xf4, 0x19, 0xd8, 0xec, 0x82, 0xb0, 0x68, 0x7f, 0x8a, 0xcb, 0x52, 0x5c, 0xa5, 0x54,
	0x2e, 0xed, 0x3a, 0x09, 0x56, 0xf9, 0x92, 0x83, 0x39, 0x05, 0x86, 0x3e, 0x03, 0x98, 0xd7, 0xf9,
	0x40, 0xe5, 0x14, 0x94, 0x3f, 0x03, 0x5a, 0xac, 0x2c, 0x22, 0xd1, 0x1c, 0x78, 0xef, 0xed, 0xb7,
	0x5f, 0xef, 0xad, 0x12, 0xda, 0xa6, 0x33, 0x5a, 0x3a, 0xd6, 0xd2, 0x89, 0xeb, 0x83, 0x3e, 0x81,
	0x64, 0x5b, 0xe8, 0xee, 0x3c, 0x4e, 0x93, 0xc1, 0x29, 0x96, 0x17, 0x50, 0x18, 0x34, 0xaa, 0xd0,
	0xee, 0xa0, 0x92, 0x46, 0xdb, 0xbb, 0x94, 0x4d, 0x32, 0x7a, 0xe2, 0xb7, 0x4f, 0xd1, 0x47, 0x00,
	0x73, 0x0e, 0xab, 0x06, 0xc1, 0x7c, 0x7c, 0x93, 0x21, 0x9b, 0x8f, 0x6f, 0x2a, 0x38, 0x78, 0x57,
	0xf1, 0xdd, 0x42, 0x38, 0x9d, 0x0f, 0x7d, 0x05, 0x70, 0x75, 0xf6, 0x96, 0xa2, 0x47, 0x73, 0xee,
	0xe4, 0x6f, 0x2f, 0x42, 0xf1, 0xf1, 0xbf, 0x89, 0x17, 0xdd, 0xed, 0x89, 0x7a, 0x69, 0x4e, 0x6b,
	0x4f, 0xcf, 0x86, 0x36, 0x38, 0x1f, 0xda, 0xe0, 0xe7, 0xd0, 0x06, 0xef, 0x46, 0x76, 0xe6, 0x7c,
	0x64, 0x67, 0xbe, 0x8f, 0xec, 0xcc, 0x61, 0xd9, 0xf3, 0xe5, 0xcb, 0xbe, 0x4b, 0x5a, 0xa2, 0x7b,
	0xc5, 0xb0, 0x37, 0x66, 0x15, 0x83, 0x88, 0xc7, 0x6e, 0x5e, 0x3d, 0xb3, 0xf7, 0x7e, 0x07, 0x00,
	0x00, 0xff, 0xff, 0x31, 0xfb, 0x3c, 0xdc, 0x2b, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a Ta by id.
	Ta(ctx context.Context, in *QueryGetTaRequest, opts ...grpc.CallOption) (*QueryGetTaResponse, error)
	// Queries a list of Ta items.
	TaAll(ctx context.Context, in *QueryAllTaRequest, opts ...grpc.CallOption) (*QueryAllTaResponse, error)
	GetAllNftByOwner(ctx context.Context, in *QueryGetAllNftByOwnerRequest, opts ...grpc.CallOption) (*QueryGetAllNftByOwnerResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/obadafoundation.fullcore.obit.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Ta(ctx context.Context, in *QueryGetTaRequest, opts ...grpc.CallOption) (*QueryGetTaResponse, error) {
	out := new(QueryGetTaResponse)
	err := c.cc.Invoke(ctx, "/obadafoundation.fullcore.obit.Query/Ta", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) TaAll(ctx context.Context, in *QueryAllTaRequest, opts ...grpc.CallOption) (*QueryAllTaResponse, error) {
	out := new(QueryAllTaResponse)
	err := c.cc.Invoke(ctx, "/obadafoundation.fullcore.obit.Query/TaAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetAllNftByOwner(ctx context.Context, in *QueryGetAllNftByOwnerRequest, opts ...grpc.CallOption) (*QueryGetAllNftByOwnerResponse, error) {
	out := new(QueryGetAllNftByOwnerResponse)
	err := c.cc.Invoke(ctx, "/obadafoundation.fullcore.obit.Query/GetAllNftByOwner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a Ta by id.
	Ta(context.Context, *QueryGetTaRequest) (*QueryGetTaResponse, error)
	// Queries a list of Ta items.
	TaAll(context.Context, *QueryAllTaRequest) (*QueryAllTaResponse, error)
	GetAllNftByOwner(context.Context, *QueryGetAllNftByOwnerRequest) (*QueryGetAllNftByOwnerResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) Ta(ctx context.Context, req *QueryGetTaRequest) (*QueryGetTaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ta not implemented")
}
func (*UnimplementedQueryServer) TaAll(ctx context.Context, req *QueryAllTaRequest) (*QueryAllTaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TaAll not implemented")
}
func (*UnimplementedQueryServer) GetAllNftByOwner(ctx context.Context, req *QueryGetAllNftByOwnerRequest) (*QueryGetAllNftByOwnerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllNftByOwner not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/obadafoundation.fullcore.obit.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Ta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetTaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Ta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/obadafoundation.fullcore.obit.Query/Ta",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Ta(ctx, req.(*QueryGetTaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_TaAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllTaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).TaAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/obadafoundation.fullcore.obit.Query/TaAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).TaAll(ctx, req.(*QueryAllTaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetAllNftByOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetAllNftByOwnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetAllNftByOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/obadafoundation.fullcore.obit.Query/GetAllNftByOwner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetAllNftByOwner(ctx, req.(*QueryGetAllNftByOwnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "obadafoundation.fullcore.obit.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "Ta",
			Handler:    _Query_Ta_Handler,
		},
		{
			MethodName: "TaAll",
			Handler:    _Query_TaAll_Handler,
		},
		{
			MethodName: "GetAllNftByOwner",
			Handler:    _Query_GetAllNftByOwner_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "obit/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetAllNftByOwnerRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetAllNftByOwnerRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetAllNftByOwnerRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetAllNftByOwnerResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetAllNftByOwnerResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetAllNftByOwnerResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.NFT) > 0 {
		for iNdEx := len(m.NFT) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.NFT[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetTaRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetTaRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetTaRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetTaResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetTaResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetTaResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Ta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllTaRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllTaRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllTaRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllTaResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllTaResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllTaResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Ta) > 0 {
		for iNdEx := len(m.Ta) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Ta[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetAllNftByOwnerRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetAllNftByOwnerResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.NFT) > 0 {
		for _, e := range m.NFT {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryGetTaRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetTaResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Ta.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllTaRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllTaResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Ta) > 0 {
		for _, e := range m.Ta {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetAllNftByOwnerRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetAllNftByOwnerRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetAllNftByOwnerRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetAllNftByOwnerResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetAllNftByOwnerResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetAllNftByOwnerResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NFT", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NFT = append(m.NFT, NFT{})
			if err := m.NFT[len(m.NFT)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetTaRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetTaRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetTaRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetTaResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetTaResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetTaResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Ta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllTaRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllTaRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllTaRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllTaResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllTaResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllTaResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ta = append(m.Ta, Ta{})
			if err := m.Ta[len(m.Ta)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
