// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: fullcore/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgCreateObitResponse struct {
	Obit *Obit `protobuf:"bytes,1,opt,name=Obit,proto3" json:"Obit,omitempty"`
}

func (m *MsgCreateObitResponse) Reset()         { *m = MsgCreateObitResponse{} }
func (m *MsgCreateObitResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateObitResponse) ProtoMessage()    {}
func (*MsgCreateObitResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_32d3384dc5197315, []int{0}
}
func (m *MsgCreateObitResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateObitResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateObitResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateObitResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateObitResponse.Merge(m, src)
}
func (m *MsgCreateObitResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateObitResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateObitResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateObitResponse proto.InternalMessageInfo

func (m *MsgCreateObitResponse) GetObit() *Obit {
	if m != nil {
		return m.Obit
	}
	return nil
}

type MsgCreateObit struct {
	SerialNumberHash string `protobuf:"bytes,1,opt,name=serialNumberHash,proto3" json:"serialNumberHash,omitempty"`
	Manufacturer     string `protobuf:"bytes,2,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	PartNumber       string `protobuf:"bytes,3,opt,name=partNumber,proto3" json:"partNumber,omitempty"`
	Creator          string `protobuf:"bytes,4,opt,name=creator,proto3" json:"creator,omitempty"`
	Owner            string `protobuf:"bytes,5,opt,name=owner,proto3" json:"owner,omitempty"`
	Signature        string `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *MsgCreateObit) Reset()         { *m = MsgCreateObit{} }
func (m *MsgCreateObit) String() string { return proto.CompactTextString(m) }
func (*MsgCreateObit) ProtoMessage()    {}
func (*MsgCreateObit) Descriptor() ([]byte, []int) {
	return fileDescriptor_32d3384dc5197315, []int{1}
}
func (m *MsgCreateObit) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateObit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateObit.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateObit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateObit.Merge(m, src)
}
func (m *MsgCreateObit) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateObit) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateObit.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateObit proto.InternalMessageInfo

func (m *MsgCreateObit) GetSerialNumberHash() string {
	if m != nil {
		return m.SerialNumberHash
	}
	return ""
}

func (m *MsgCreateObit) GetManufacturer() string {
	if m != nil {
		return m.Manufacturer
	}
	return ""
}

func (m *MsgCreateObit) GetPartNumber() string {
	if m != nil {
		return m.PartNumber
	}
	return ""
}

func (m *MsgCreateObit) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreateObit) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *MsgCreateObit) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func init() {
	proto.RegisterType((*MsgCreateObitResponse)(nil), "obadafoundation.fullcore.fullcore.MsgCreateObitResponse")
	proto.RegisterType((*MsgCreateObit)(nil), "obadafoundation.fullcore.fullcore.MsgCreateObit")
}

func init() { proto.RegisterFile("fullcore/tx.proto", fileDescriptor_32d3384dc5197315) }

var fileDescriptor_32d3384dc5197315 = []byte{
	// 325 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0x4d, 0x4b, 0x3b, 0x31,
	0x10, 0xc6, 0x9b, 0x7f, 0x5f, 0xfe, 0x74, 0x54, 0xd0, 0xa8, 0x10, 0x8a, 0x04, 0xed, 0x45, 0x11,
	0xdc, 0x4a, 0x45, 0x10, 0xbc, 0xe9, 0xc5, 0x4b, 0x2d, 0x14, 0x4f, 0xde, 0x92, 0x6d, 0xba, 0x0d,
	0xb4, 0xc9, 0x92, 0x17, 0xac, 0x27, 0xbf, 0x82, 0x1f, 0xcb, 0x8b, 0xd0, 0xa3, 0x47, 0x69, 0xbf,
	0x88, 0x34, 0xa5, 0xbb, 0x5d, 0x3c, 0xa8, 0xb7, 0x99, 0x67, 0xe6, 0xf9, 0x85, 0xcc, 0x03, 0x3b,
	0x03, 0x3f, 0x1a, 0xc5, 0xda, 0x88, 0x96, 0x9b, 0x44, 0xa9, 0xd1, 0x4e, 0xe3, 0x23, 0xcd, 0x59,
	0x9f, 0x0d, 0xb4, 0x57, 0x7d, 0xe6, 0xa4, 0x56, 0xd1, 0x6a, 0x25, 0x2b, 0x1a, 0xbb, 0x99, 0x4b,
	0x73, 0xe9, 0x96, 0xbe, 0xe6, 0x03, 0xec, 0x77, 0x6c, 0x72, 0x6b, 0x04, 0x73, 0xa2, 0xcb, 0xa5,
	0xeb, 0x09, 0x9b, 0x6a, 0x65, 0x05, 0xbe, 0x86, 0xca, 0xa2, 0x27, 0xe8, 0x10, 0x9d, 0x6c, 0xb4,
	0x8f, 0xa3, 0x1f, 0xf9, 0x51, 0xb0, 0x07, 0x53, 0xf3, 0x1d, 0xc1, 0x56, 0x01, 0x8b, 0x4f, 0x61,
	0xdb, 0x0a, 0x23, 0xd9, 0xe8, 0xde, 0x8f, 0xb9, 0x30, 0x77, 0xcc, 0x0e, 0x03, 0xba, 0xde, 0xfb,
	0xa6, 0xe3, 0x26, 0x6c, 0x8e, 0x99, 0xf2, 0x03, 0x16, 0x3b, 0x6f, 0x84, 0x21, 0xff, 0xc2, 0x5e,
	0x41, 0xc3, 0x14, 0x20, 0x65, 0xc6, 0x2d, 0x5d, 0xa4, 0x1c, 0x36, 0xd6, 0x14, 0x4c, 0xe0, 0x7f,
	0xbc, 0x78, 0x5d, 0x1b, 0x52, 0x09, 0xc3, 0x55, 0x8b, 0xf7, 0xa0, 0xaa, 0x9f, 0x94, 0x30, 0xa4,
	0x1a, 0xf4, 0x65, 0x83, 0x0f, 0xa0, 0x6e, 0x65, 0xa2, 0xd8, 0x82, 0x4e, 0x6a, 0x61, 0x92, 0x0b,
	0xed, 0x17, 0x28, 0x77, 0x6c, 0x82, 0x27, 0x00, 0x6b, 0x5f, 0x3a, 0xff, 0xc5, 0x4d, 0x0a, 0x47,
	0x68, 0x5c, 0xfd, 0xd5, 0xb1, 0x4a, 0xe3, 0xa6, 0xfb, 0x36, 0xa3, 0x68, 0x3a, 0xa3, 0xe8, 0x73,
	0x46, 0xd1, 0xeb, 0x9c, 0x96, 0xa6, 0x73, 0x5a, 0xfa, 0x98, 0xd3, 0xd2, 0xe3, 0x65, 0x22, 0xdd,
	0xd0, 0xf3, 0x28, 0xd6, 0xe3, 0x56, 0xa0, 0x9f, 0xe5, 0xf8, 0x56, 0x96, 0xf8, 0x24, 0x2f, 0xdd,
	0x73, 0x2a, 0x2c, 0xaf, 0x85, 0xf8, 0x2f, 0xbe, 0x02, 0x00, 0x00, 0xff, 0xff, 0x6b, 0x04, 0x5b,
	0xf8, 0x4b, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	CreateObit(ctx context.Context, in *MsgCreateObit, opts ...grpc.CallOption) (*MsgCreateObitResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreateObit(ctx context.Context, in *MsgCreateObit, opts ...grpc.CallOption) (*MsgCreateObitResponse, error) {
	out := new(MsgCreateObitResponse)
	err := c.cc.Invoke(ctx, "/obadafoundation.fullcore.fullcore.Msg/CreateObit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	CreateObit(context.Context, *MsgCreateObit) (*MsgCreateObitResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CreateObit(ctx context.Context, req *MsgCreateObit) (*MsgCreateObitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateObit not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CreateObit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateObit)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateObit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/obadafoundation.fullcore.fullcore.Msg/CreateObit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateObit(ctx, req.(*MsgCreateObit))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "obadafoundation.fullcore.fullcore.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateObit",
			Handler:    _Msg_CreateObit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fullcore/tx.proto",
}

func (m *MsgCreateObitResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateObitResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateObitResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Obit != nil {
		{
			size, err := m.Obit.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateObit) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateObit) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateObit) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.PartNumber) > 0 {
		i -= len(m.PartNumber)
		copy(dAtA[i:], m.PartNumber)
		i = encodeVarintTx(dAtA, i, uint64(len(m.PartNumber)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Manufacturer) > 0 {
		i -= len(m.Manufacturer)
		copy(dAtA[i:], m.Manufacturer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Manufacturer)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.SerialNumberHash) > 0 {
		i -= len(m.SerialNumberHash)
		copy(dAtA[i:], m.SerialNumberHash)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SerialNumberHash)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCreateObitResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Obit != nil {
		l = m.Obit.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCreateObit) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SerialNumberHash)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Manufacturer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.PartNumber)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCreateObitResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateObitResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateObitResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Obit", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Obit == nil {
				m.Obit = &Obit{}
			}
			if err := m.Obit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateObit) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateObit: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateObit: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SerialNumberHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SerialNumberHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Manufacturer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Manufacturer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PartNumber", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PartNumber = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
