name: "Tests"
on:
  workflow_call:
defaults:
  run:
    shell: bash

jobs:
  go-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod
          cache: true

      - name: test
        run: |
          go test -race -ldflags "-X google.golang.org/protobuf/reflect/protoregistry.conflictPolicy=warn" -timeout=60s -covermode=atomic -coverprofile=$GITHUB_WORKSPACE/profile.cov_tmp ./...
          cat $GITHUB_WORKSPACE/profile.cov_tmp | grep -v "_mock.go" > $GITHUB_WORKSPACE/profile.cov
        working-directory: .
        env:
          GOFLAGS: "-mod=vendor"
          TZ: "America/New_York"

      - name: install goveralls
        run: |
          GO111MODULE=off go get -u github.com/mattn/goveralls
      - name: submit coverage
        run: $(go env GOPATH)/bin/goveralls -service="github" -coverprofile=$GITHUB_WORKSPACE/profile.cov
        working-directory: .
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
